// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_PUBLIC =  "GET_PRODUCTS_PUBLIC";
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SEARCH_PRODUCT_NAME = 'SEARCH_PRODUCT_NAME';
export const SEARCH_PRODUCT_NAME_PUBLIC = 'SEARCH_PRODUCT_NAME_PUBLIC';
export const SEARCH_PRODUCT_ID = 'SEARCH_PRODUCT_ID';
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const ORDER_PRODCTS = "ORDER_PRODCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

// Categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const SEARCH_CATEGORY_NAME = 'SEARCH_CATEGORY_NAME';

// Users
export const GET_USERS = "GET_USERS";
export const CREATE_USER = "CREATE_USER";
export const DELETE_USER = "DELETE_USER";
export const PROMOTE_USER = "PROMOTE_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SIGN_IN = "SIGN_IN";
export const SUCCESS_SESSION = "CHECK_SESSION";
export const FAIL_SESSION = "SET_SESSION";
export const LOGOUT="LOGOUT"
export const USER_ORDERS = 'USER_ORDERS'
export const USER_REVIEWS = 'USER_REVIEWS'


// Orders / Shopping
export const GET_ORDERS = "GET_ORDERS";
export const FILTER_ORDERS = "FILTER_ORDERS";
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const CREATE_SHOPPING_SESSION = "CREATE_SHOPPING_SESSION";
export const DELETE_SHOPPING_SESSION = "DELETE_SHOPPING_SESSION";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const EDIT_CART_ITEM_QTY = "EDIT_CART_ITEM_QUANTITY";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_CART = "DELETE_CART";
// Misc
export const ADD_OR_UPDATE = "ADD_OR_UPDATE";

// Local Storage
export const SAVE_LOCAL_STORAGE = "SAVE_LOCAL_STORAGE";
export const GET_LOCAL_STORAGE = "GET_LOCAL_STORAGE";
export const DELETE_ITEM_LOCAL_STORAGE = "DELETE_ITEM_LOCAL_STORAGE";
export const EDIT_LOCAL_STORAGE_QTY = "EDIT_LOCAL_STORAGE_QTY";
export const UPDATE_SUBTOTAL = "UPDATE_SUBTOTAL";